
<?php 
$words = explode('/', $_SERVER['REQUEST_URI']);
$uidt = trim($words[count($words) - 1], '/')+"";
//$uid= 1;
if($uidt ==""){
    $uid="1";
}else{
     $uid=$uidt;
}

?>

<html><head>
  <title>MegaPersonals: Classified hookups</title>
  <meta id="viewportMetaTag" name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE">
  <meta charset="utf-8">

  
    
    
      <meta name="ROBOTS" content="INDEX, FOLLOW">
    
  

  <meta name="google-site-verification" content="5lgcaPvrDxOjE8Qn9rMbYKiJVahMPVReOQvezzd1nRY">
  <meta name="description" content="MegaPersonals - Post your classified ad and MEET NOW">
   <link rel="icon" href="/resources/img/devilgirl_favicon.ico" type="image/x-icon">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="/resources/css/custom.css">
  <link rel="stylesheet" href="/resources/css/emojionearea.min.css?v=1650485155">
  <!-- The newest version could cause errors in Safari -->
  <script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script type="text/javascript" async="" src="https://mc.yandex.ru/metrika/tag.js"></script><script type="text/javascript" async="" src="https://www.gstatic.com/recaptcha/releases/QENb_qRrX0-mQMyENQjD6Fuj/recaptcha__en.js" crossorigin="anonymous" integrity="sha384-GLJMwNj3546zgUVjrd41QmXS0fdK5/SrrvaM33bRtDDYeW5KygkcPN+lQPjFA6D+"></script><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js" type="text/javascript"></script>
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="/resources/js/emojionearea.min.js?v=1650485155"></script>
  <script src="/resources/js/anti_clicker.js?v=1650485155" type="text/javascript"></script>
  <!-- Yandex.Metrika counter -->
  <script type="text/javascript">
      (function (d, w, c) {
          (w[c] = w[c] || []).push(function() {
              try {
                  w.yaCounter51410560 = new Ya.Metrika2({
                      id:51410560,
                      clickmap:true,
                      trackLinks:true,
                      accurateTrackBounce:true
                  });
              } catch(e) { }
          });
          var n = d.getElementsByTagName("script")[0],
              s = d.createElement("script"),
              f = function () { n.parentNode.insertBefore(s, n); };
          s.type = "text/javascript";
          s.async = true;
          s.src = "https://mc.yandex.ru/metrika/tag.js";
          if (w.opera == "[object Opera]") {
              d.addEventListener("DOMContentLoaded", f, false);
          } else { f(); }
      })(document, window, "yandex_metrika_callbacks2");
  </script>
  <noscript><div><img src="https://mc.yandex.ru/watch/51410560" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  <!-- /Yandex.Metrika counter -->

  <!-- Generated by Revive Adserver -->
  <script type="text/javascript" src="https://itransitauthority.com/www/delivery/spcjs.php?id=10"></script><script type="text/javascript" src="https://itransitauthority.com/www/delivery/spc.php?zones=48%7C49%7C50%7C51&amp;source=&amp;r=38318045&amp;charset=UTF-8&amp;loc=https%3A//megapersonals.eu/users/register&amp;referer=https%3A//megapersonals.eu/users/auth/login"></script><script type="text/javascript" src="https://itransitauthority.com/www/delivery/fl.js"></script>

  <!--end of revive-->

</head>

<body>
<div class="container register-page">
    <a href="/home">
        <img src="/resources/img/megapersonalsPageHeader.png?v=1650485155" class="img-responsive center-block img-width-72 haeder-top-margin" alt="Megapersonals" id="megapersonalsPageHeader">
    </a>
    <div class="centered padd-top-25">

    </div>
    
    <form id="registerForm" class="loginwrapper" action="/users/register" method="post" autocomplete="false">
        <div class="loginwrapper">
            
                
                    <div class="centered">
                        <h2 class="gray bold loginlabel">
                            Create New Login
                        </h2>
                        <input id="person_email_field_signup" name="email" class="form-control width-285 bordered three-radius" placeholder="E-mail" type="text" value="">
                        
                    </div>
                    <div class="centered">
                        <input id="person_password_field_signup" name="password" class="form-control bordered three-radius" placeholder="Password" type="password" value="">
                        
                    </div>

                    <div class="centered">
                        <input id="person_confirmPassword_field_signup" name="confirmPassword" class="form-control bordered three-radius" placeholder="Confirm password" type="password" value="">
                        
                    </div>
                
                
            


            <div class="checkbox agechecker">
                <label>
                    <input type="checkbox" name="agecheck" id="checkage">
                    I certify that I am 21 years of age or older, that I am placing ads for myself, under my own phone
                    number and that I am abiding by all local laws and regulations.
                </label>
            </div>
            <br>
            <div class="centered automargin">
                <div style="display: inline-block">
                    





    <div class="g-recaptcha" data-sitekey="6LdDSG4UAAAAANv7vDF_spZrXcSC0JvorM_2N2WQ"><div style="width: 304px; height: 78px;"><div><iframe title="reCAPTCHA" src="https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdDSG4UAAAAANv7vDF_spZrXcSC0JvorM_2N2WQ&amp;co=aHR0cHM6Ly9tZWdhcGVyc29uYWxzLmV1OjQ0Mw..&amp;hl=en&amp;v=QENb_qRrX0-mQMyENQjD6Fuj&amp;size=normal&amp;cb=tgps6rsz8ro5" width="304" height="78" role="presentation" name="a-1t0on7pnssin" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation"></iframe></div><textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid rgb(193, 193, 193); margin: 10px 25px; padding: 0px; resize: none; display: none;"></textarea></div><iframe style="display: none;"></iframe></div>

                    <br>
                    
                </div>
                <button id="sign_up_data_submit_button" type="button" class="myButton top-margin-55" aria-haspopup="true" disabled="disabled">Submit
                </button>
            </div>

            <div class="centered top-margin-55">
                <a href="/users/auth/login/<?php echo $uid ?>" class="linksUnderButton">Already have a login?</a>
            </div>
        </div>
    </form>
    <br><br>
</div>

<script type="text/javascript">
    $(function () {
        $('#sign_up_data_submit_button').attr('disabled', true);
    });

    $('#checkage').change(function (e) {
        $('#sign_up_data_submit_button').attr('disabled', !this.checked);
    });

    $('#sign_up_data_submit_button').on('click', function(ev){
        if (grecaptcha && grecaptcha.getResponse().length > 0) {
            $('form').submit();
        } else {
            warningDlg($('#warning-message-dlg'), $('#warning-msg-body-id'), "Captcha should not be empty");
        }
    });

</script>





































































    
        
        
        
        
    
    
    




    
    
        
    


<footer>
    <nav>
        <ul class="pager myStyle">
            <li>
                <a id="homeclick" href="/home">Home</a>
            </li>
            
            <li>|</li>
            <li><a href="/public/contact_us">Contact Us</a></li>
            <li>|</li>
            <li><a href="/public/terms">Policies &amp; Terms</a></li>

            
            
        </ul>
        <p class="buglink"><a href="/public/report_bug">Report Bug</a></p>
    </nav>

    <div class="copyright_class" id="copyrigh">Copyright ©2021 MegaPersonals.eu 
<div style="padding-top:10px"> 
For support email <a href="mailto:support@megapersonals.eu">support@megapersonals.eu</a>
</div> </div>

    <div class="clearfix">
    

    
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    


    <input type="hidden" class="jsp-env" data-escortbabylon="escortbabylon.com" data-imagedomain1="img1.lodef.net/imgs" data-imagedomain2="img2.lodef.net/imgs" data-videodomain1="video1.lodef.net/video" data-videodomain2="video2.lodef.net/video" data-videodomain3="video3.lodef.net/video" data-videodomain4="video4.lodef.net/video" data-imagemiddle="80000000000000000000000000000000" data-image2middle="40000000000000000000000000000000" data-image3middle="c0000000000000000000000000000000" data-imageupload="image-processor.apnot.com/process" data-imagepreview="image-processor.apnot.com/static" data-deletedimage="image-processor-master.gomofo.net/deleted_images" data-captchaapi="captcha.lodef.net/api/captcha" data-captchaurl="captcha.lodef.net/captchas" data-lcdomain="listcrawler.com" data-transactionnocontexttoken="NO_CONTEXT_TRANSACTION_TOKEN" data-usertermsofageversion="2">

</div>

    <script src="/resources/js/image_utils.js?v=1650485155" type="text/javascript"></script>
    <script src="/resources/js/video_utils.js?v=1650485155" type="text/javascript"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-113349993-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-113349993-1');
    </script>

</footer>



<div style="background-color: rgb(255, 255, 255); border: 1px solid rgb(204, 204, 204); box-shadow: rgba(0, 0, 0, 0.2) 2px 2px 3px; position: absolute; transition: visibility 0s linear 0.3s, opacity 0.3s linear 0s; opacity: 0; visibility: hidden; z-index: 2000000000; left: 0px; top: -10000px;"><div style="width: 100%; height: 100%; position: fixed; top: 0px; left: 0px; z-index: 2000000000; background-color: rgb(255, 255, 255); opacity: 0.05;"></div><div class="g-recaptcha-bubble-arrow" style="border: 11px solid transparent; width: 0px; height: 0px; position: absolute; pointer-events: none; margin-top: -11px; z-index: 2000000000;"></div><div class="g-recaptcha-bubble-arrow" style="border: 10px solid transparent; width: 0px; height: 0px; position: absolute; pointer-events: none; margin-top: -10px; z-index: 2000000000;"></div><div style="z-index: 2000000000; position: relative;"><iframe title="recaptcha challenge expires in two minutes" src="https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=QENb_qRrX0-mQMyENQjD6Fuj&amp;k=6LdDSG4UAAAAANv7vDF_spZrXcSC0JvorM_2N2WQ" name="c-1t0on7pnssin" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation" style="width: 100%; height: 100%;"></iframe></div></div></body></html>