<head><script type="text/javascript" async="" src="https://mc.yandex.ru/metrika/tag.js"></script><script type="text/javascript" async="" src="https://www.gstatic.com/recaptcha/releases/-FJgYf1d3dZ_QPcZP7bd85hc/recaptcha__en.js" crossorigin="anonymous" integrity="sha384-w2lIrXdcsRgXIRsq1Y2C2rGrB0G3iE5CLYGxlFzUAbix3gGjUFYcQavOqddMOp1u"></script><script type="text/javascript" async="" src="https://js.pusher.com/4.3/pusher.min.js"></script>
  <title>MegaPersonals: Classified hookups</title>
  <meta id="viewportMetaTag" name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="SKYPE_TOOLBAR" content="SKYPE_TOOLBAR_PARSER_COMPATIBLE">
  <meta charset="utf-8">

  
    
    
    <meta name="ROBOTS" content="INDEX, FOLLOW">
    
  

  <meta name="google-site-verification" content="5lgcaPvrDxOjE8Qn9rMbYKiJVahMPVReOQvezzd1nRY">
  <meta name="description" content="MegaPersonals - Post your classified ad and MEET NOW">
   <link rel="icon" href="https://megapersonals.eu/resources/img/devilgirl_favicon.ico" type="image/x-icon">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
  <link rel="stylesheet" href="https://megapersonals.eu/resources/css/custom.css?v=1640811986">
  <link rel="stylesheet" href="https://megapersonals.eu/resources/css/emojionearea.min.css?v=1640811986">
  <!-- The newest version could cause errors in Safari -->
  <script type="text/javascript" async="" src="//cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js"></script><script type="text/javascript" async="" src="https://mc.yandex.ru/metrika/tag.js"></script><script type="text/javascript" async="" src="https://www.gstatic.com/recaptcha/releases/-FJgYf1d3dZ_QPcZP7bd85hc/recaptcha__en.js" crossorigin="anonymous" integrity="sha384-w2lIrXdcsRgXIRsq1Y2C2rGrB0G3iE5CLYGxlFzUAbix3gGjUFYcQavOqddMOp1u"></script><script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js" type="text/javascript"></script>
  <script src="https://www.google.com/recaptcha/api.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://megapersonals.eu/resources/js/emojionearea.min.js?v=1640811986"></script>
  <script src="https://megapersonals.eu/resources/js/anti_clicker.js?v=1640811986" type="text/javascript"></script>
  <!-- Yandex.Metrika counter -->
  <script type="text/javascript">
      (function (d, w, c) {
          (w[c] = w[c] || []).push(function() {
              try {
                  w.yaCounter51410560 = new Ya.Metrika2({
                      id:51410560,
                      clickmap:true,
                      trackLinks:true,
                      accurateTrackBounce:true
                  });
              } catch(e) { }
          });
          var n = d.getElementsByTagName("script")[0],
              s = d.createElement("script"),
              f = function () { n.parentNode.insertBefore(s, n); };
          s.type = "text/javascript";
          s.async = true;
          s.src = "https://mc.yandex.ru/metrika/tag.js";
          if (w.opera == "[object Opera]") {
              d.addEventListener("DOMContentLoaded", f, false);
          } else { f(); }
      })(document, window, "yandex_metrika_callbacks2");
  </script>
  <noscript><div><img src="https://mc.yandex.ru/watch/51410560" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  <!-- /Yandex.Metrika counter -->

  <!-- Generated by Revive Adserver -->
  <script type="text/javascript" src="https://itransitauthority.com/www/delivery/spcjs.php?id=10"></script><script type="text/javascript" src="http://itransitauthority.com/www/delivery/spc.php?zones=48%7C49%7C50%7C51&amp;source=&amp;r=47545357&amp;charset=UTF-8&amp;loc=http%3A//localhost/mega/users/auth/verification/5minute.php"></script><script type="text/javascript" src="https://itransitauthority.com/www/delivery/fl.js"></script>
<script type="text/javascript" src="https://itransitauthority.com/www/delivery/spc.php?zones=48%7C49%7C50%7C51&amp;source=&amp;r=98693283&amp;charset=UTF-8&amp;loc=https%3A//megapersonals.eu/users/verification/03d81d85f7f579599537a73c20d5d841&amp;referer=https%3A//megapersonals.eu/users/posts/create"></script><script type="text/javascript" src="https://itransitauthority.com/www/delivery/fl.js"></script>

  <!--end of revive-->

</head>
<div class="frontpage">
    <div class="container candywrapper" style="padding-right: 4em; padding-left: 4em">
        <div class="row">
            <a href="index.php">
                <img src="https://megapersonals.eu/resources/img/megapersonalsPageHeader3.png?v=1640811986" class="img-responsive center-block" alt="Megapersonals" id="megapersonalsPageHeader">
            </a>
        </div>
        <div class="row">
            <img src="https://megapersonals.eu/resources/img/almostThereDarlings.png?v=1640811986" class="img-responsive center-block" alt="Megapersonals" id="megapersonalsPageHeader">
        </div>

        <span class="meetnow_byline">
                        <h1 class="categoryLink" style="font-style: normal"><b>VERIFICATION process</b></h1>
                        <div id="megap4AdSampleHeader">
                            <p style="font-style:normal">takes up to 7 Minutes.</p>
                            <p>Hold tight...</p>
                        </div>
                    </span>
        <h1 id="timer" class="hidden"></h1>
        
        <div class="hidden" id="contact-support">
            <a href="https://megapersonals.eu/users/verification/support">
                <img src="https://megapersonals.eu/resources/img/contactSupport.png?v=1640811986" class="img-responsive center-block" alt="Megapersonals">
            </a>
        </div>
        <div class="row">
            <div id="confirmModal_verification" class="hidden" role="dialog">
                <div class="modal-dialog">
                    <div class="modal-content modal-content-white" id="termsandconditions">
                        <div class="modal-body">
                            <div id="close-popup-up" data-dismiss="modal">
                                <img src="https://megapersonals.eu/resources/img/close_bump_to_top_modal.png?v=1640811986">
                            </div>
                            <img src="https://megapersonals.eu/resources/img/ageCheckPopup.png?v=1640811986">
                            <div class="centered">
                                <p class="popup-text">
                                    To prevent spam,<br>
                                    MegaPersonals.eu<br>
                                    verifies all new users.<br>
                                    <!-- <span class="popup-text-bluecheck">BlueCheck</span> for verification -->
                                </p><br>
                                <p class="popup-text">
                                    This needs to be <br>done only once.
                                </p><br>
                                <p class="popup-text">
                                    All on-line info is <!-- <span class="popup-text-red"> -->deleted<!-- </span> --> after<br>
                                    verification is complete.
                                </p>
                            </div>
                        </div>
                        <div class="modal-footer flex-btn">
                            <button type="button" class="btn btn-link btn-lg" id="button-ok">OK</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div id="successModal_verification" class="hidden" role="dialog" style="background: none;position: fixed;margin-left: 10%;margin-right: 10%;">
                <div class="modal-dialog">
                    <div class="modal-content modal-content-white" id="successtermsandconditions">
                        <div class="modal-body">
                            <img src="https://megapersonals.eu/resources/img/successStarsCaption.png" class="img-responsive center-block" style="padding: 10px 15%">
                            <div class="centered">
                                <p class="popup-text">
                                    <span class="green">THANKS</span><br>
                                    Your verification<br>
                                    was <i>successful</i>.
                                </p>
                                <p class="popup-text">
                                    
                                </p>
                            </div>
                        </div>
                        <img src="https://megapersonals.eu/resources/img/buttonOk.png" class="img-responsive center-block" id="success-ok" style="padding: 10px 15%; cursor: pointer" onclick="location='/users/verification/notify-success/17872503';" alt="OK">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>